[package]
name = "smplinfo-gui"
version = "0.1.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
edition = "2021"

[lib]
path = "widgets/mod.rs"

[dependencies]
eframe = "0.16"
id_tree = "1.8"
serde = { version ="1.0", features = ["derive"] }
